### ISSUE TITLE
Is there a way how to add an empty line between 2 list items?

### ISSUE THREAD

**Issue by dmitrykinakh** [ckeditor/ckeditor5-list#105]
Is there a way how to add an empty line between 2 list items? It was working in CKEditor 4 when you press SHIFT + ENTER it adds you an empty line. Unfortunately, it doesn't happen in CKEditor 5.

**Comment by Reinmar** [comment]
Empty line between two list items? Could you show an HTML version of what you'd expect? 

Please do mind that [shift+enter support](https://github.com/ckeditor/ckeditor5-enter/pull/54) will be introduced in the upcoming release.

**Comment by dmitrykinakh** [comment]
Hi @Reinmar, please see my video with shows how it works in CKEditor 5 and CKEditor 4 - http://take.ms/90DY8

**Comment by pomek** [comment]
@Reinmar, after pressing Shift+enter at the end of the list item, I have:

![image](https://user-images.githubusercontent.com/2270764/41403009-13292aa8-6fc4-11e8-8cff-98b7bd85a45f.png)

And I cannot typing in the blank line.

I guess it's about the block filler as we had here – https://github.com/ckeditor/ckeditor5-engine/issues/1422.

**Comment by Reinmar** [comment]
@pomek, if you see any problem with typing after shift+enter inside lists, please report a separate issue.
