### ISSUE TITLE
Coverage dropped

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-list#107]
![image](https://user-images.githubusercontent.com/156149/42277599-2e57c9fe-7f98-11e8-8688-3c30d99d743f.png)

After introducing the selection post-fixer.

**Comment by jodator** [comment]
Coverage will be restored in #108 to previous:
![selection_013](https://user-images.githubusercontent.com/247363/42508665-9de6d534-8449-11e8-94aa-a2e5308404e1.png)
