### ISSUE TITLE
Divs inside list items break lists

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5-list#116]
Evernote produces lists like this:

```
<ul>
    <li>
        <div>item 1</div>
    </li>
    <li>
        <div>item 2</div>
    </li>
</ul>
```

Of course the div is redundant here, but otherwise it looks fine to me. But CKEditor converts it to this:

![image](https://user-images.githubusercontent.com/617641/47969570-b3fa7380-e079-11e8-89f0-c7f8ea88da7e.png)

So the list is lost. That doesn't look right to me?

**Comment by Reinmar** [comment]
cc @f1ames

**Comment by f1ames** [comment]
Thanks for reporting @zadam.

This is a known issue (reported in https://github.com/ckeditor/ckeditor5/issues/1318). At the moment, block elements are not allowed inside lists so they get "extracted" outside during content conversion/upcasting (from HTML to view and then to model). This results in regular block content and empty list (which gest removed).

Please follow this issue in https://github.com/ckeditor/ckeditor5/issues/1318 (you may also +1/👍if you find the fix important).
