### ISSUE TITLE
Todo list + RTL support

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-list#134]
In RTL you use opposite arrows to move between list items, so most probably we should check and fix how selection jump over UI elements in todo lists in RTL.

**Comment by oleq** [comment]
Is this related https://github.com/ckeditor/ckeditor5-widget/issues/97?

**Comment by pjasiun** [comment]
Kind of. I do not think it is directly connected, because todo has its own implementation of arrows handling, but the problem is similar.

**Comment by Reinmar** [comment]
I'm assign this to it27 because it seems that it can be fixed together with https://github.com/ckeditor/ckeditor5-widget/issues/97. If not, we can postpone this one.

**Comment by AnnaTomanek** [comment]
FYI, another issue that we encountered when working on the screenshot for the release blog post was this:

![Screenshot 2019-08-29 at 13 41 30](https://user-images.githubusercontent.com/538321/63943241-83a01d80-ca6f-11e9-87be-88516ab8c0da.png)

@dkonopka provided some quick fixes for this in https://github.com/ckeditor/ckeditor5/commit/717cb4a05a536af07b143169ad6d9029d49478ec and https://github.com/ckeditor/ckeditor5/commit/43d99eebffac9777531d21b30155a44fb321e5e8.

**Comment by jodator** [comment]
Closed by  63deb51.
