### ISSUE TITLE
Improve styles of todo list

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-list#136]
Follow-up: https://github.com/ckeditor/ckeditor5-list/pull/133

We should check if todo lists (especially checkmark element) looks good with different `font-family` and `font-size` styles.

**Comment by oleq** [comment]
https://github.com/ckeditor/ckeditor5-list/blob/master/theme/list.css#L66

should be

```css
border: solid hsl(0, 0%, 100%);
```

and the check should not have `top` but `vertical-align: middle;`

![image](https://user-images.githubusercontent.com/1099479/63262504-71abc700-c286-11e9-832a-528d86293cdd.png)

**Comment by elszczepano** [comment]
Unchecked item has a white selection mark on select

![Screenshot 2019-08-21 at 11 45 52](https://user-images.githubusercontent.com/23155008/63422417-9c268d00-c40a-11e9-8318-cfa2e9f0ff60.png)
