### ISSUE TITLE
Todo list in demo are styled incorectly

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-list#137]
![Screenshot 2019-08-13 at 16 34 30](https://user-images.githubusercontent.com/1166967/62953371-b1d5fa00-bded-11e9-905f-c8183912f937.png)

**Comment by oskarwrobel** [comment]
Strongly related (or even a DUP) https://github.com/ckeditor/ckeditor5-list/issues/136.

**Comment by pjasiun** [comment]
I also can not select an image if it is next to the todo list (works with bullet list). I believe this is also a styling issue.

![image-click](https://user-images.githubusercontent.com/1166967/63019389-77c33180-be9b-11e9-9e33-e27659756d39.gif)
