### ISSUE TITLE
Add options parameter to _doExecute method of ListCommand with batch option

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-list#14]
Problem: I can't provide custom batch for ListCommand to group operations. The current implementation has no arguments. Best practice would be to use an object for all current and future options.

**Comment by scofalik** [comment]
Two things:
1) It will be done some day, and we will have to refactor this part of code.
2) I don't know what exactly case this is, but I believe that typing and replacing by list/heading should be two undo steps. So my question is what are you trying to achieve?

**Comment by Reinmar** [comment]
For autoformat, the command must be executed together with an operation which deletes the "* " characters. That's why it needs to accept the batch.

So, we'll have to do this change now.

**Comment by Reinmar** [comment]
Yy... In fact, it's done already :D.

**Comment by scofalik** [comment]
Okay, I see, thanks.
