### ISSUE TITLE
Should to-do list provide content styles?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-list#147]
Currently, they don't. Perhaps that's fine because we output HTML which tell the whole story. But I just wanted to verify this with you, guys.

**Comment by Reinmar** [comment]
cc @pjasiun

**Comment by Reinmar** [comment]
cc @oleq

**Comment by Reinmar** [comment]
Discussed this with guys and it should because the content of the editor may be displayed for reading, not for editing. Case: GitHub.

**Comment by oleq** [comment]
TBH I'm not sure if this makes sense. Check out [this fiddle](https://jsfiddle.net/rf05p2dj/) with unstyled content ATM:

![image](https://user-images.githubusercontent.com/1099479/66032853-76f76500-e506-11e9-81f7-d0f9042750e4.png)

In theory, we could display nice and pretty green checkboxes but does it make any sense?

**Comment by oleq** [comment]
OTOH, on the second thought, if we style images and [mentions](https://github.com/ckeditor/ckeditor5-mention/issues/90), maybe it does make sense.

**Comment by oleq** [comment]
And most of all, **how come UI component style (`ListItemView`) got totally mixed up with `List` (feature) styles in the first place?**

https://github.com/ckeditor/ckeditor5-theme-lark/blob/master/theme/ckeditor5-ui/components/list/list.css#L11-L24

This is unacceptable and just evil 😛

**Comment by oleq** [comment]
Related https://github.com/ckeditor/ckeditor5/issues/2063.
