### ISSUE TITLE
CkEditor 5 lists do not auto indent

### ISSUE THREAD

**Issue by droyson** [ckeditor/ckeditor5-list#156]
CkEditor 5 does not add the indentation for numbered/bulleted lists. This includes the child elements as well.

The auto indentation seems to work when I have an indented block and then I convert it to list.

Check the screen recording to better understand the issue.
![ScreenRecording2019-09-23at10032](https://user-images.githubusercontent.com/28538540/65409193-b639fd80-de04-11e9-9b89-ab4ce9bcba4a.gif)

**Comment by Mgsy** [comment]
Hello, just to be sure - you want to create a list, then apply indentation to it?

**Comment by droyson** [comment]
The nested list is also not indented as you can see in the screen
recording.
But when an indentation is provided prior to the creation of the list, it
seems to work correctly.

Thanks,
Royson

**Comment by jodator** [comment]
This is a bug, reported here: https://github.com/ckeditor/ckeditor5-indent/issues/13 and here: https://github.com/ckeditor/ckeditor5-engine/issues/1228.
