### ISSUE TITLE
Provide UI icon(s) for the feature

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-list#2]
They should land in `theme/icons/name.svg`

**Comment by oleq** [comment]
It turned out that [Lark](https://github.com/ckeditor/ckeditor5-theme-lark) provides list icons already, `bulletedlist` and `numberedlist`. The only task here is to copy them to `theme/icons` directory in this project and start using via `IconManager`.

**Comment by Reinmar** [comment]
Done in #1.
