### ISSUE TITLE
Cannot exit a nested list

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-list#24]
* Start with an empty editor, so you feel better the pain.
 * Create a nested list and selection like this:

```
 * Level 1
   * Level 2[]
```

 * Hit ENTER 3 times to get out of the list and start a paragraph.

It'll not work. An error is thrown.

The list cannot be finished by using ENTER, BACKSPACE or even the toolbar button. You simply get stuck.

**Comment by fredck** [comment]
It'll not work even if you start with this:

```
 * Level 1
   * Level 2
 * Level 1 again[]
```

**Comment by fredck** [comment]
A similar TC, with different result:

 * Create a nested list, a paragraph, and selection like this:

```
 * Level 1
    * Level 2[]

A normal paragraph.
```

 * Hit ENTER 3 times to exit the list.

The caret will end up after the paragraph.

**Comment by scofalik** [comment]
I can't reproduce any of these, but during testing different scenarios, I found other bugs.
