### ISSUE TITLE
Error thrown when redoing removing a list

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-list#51]
1. Go to http://localhost:8125/ckeditor5-list/tests/manual/nestedlists.html.
2. Press <kbd>Ctrl+A</kbd> and <kbd>Backspace</kbd> (currently it leaves one empty list item – mind that it may change in the future).
5. Press <kbd>Ctrl+Z</kbd> once.
6. Press <kbd>Ctrl+Y</kbd> once.

Error is thrown:

```
Uncaught CKEditorError: attribute-operation-wrong-old-value: Changed node has different attribute value than operation's old attribute value. {"item":{"name":"$graveyardHolder"},"key":"indent","value":2}
```

**Comment by Reinmar** [comment]
I updated the description because it turned out that it doesn't require pasting.

**Comment by scofalik** [comment]
https://github.com/ckeditor/ckeditor5-engine/issues/891
