### ISSUE TITLE
View-to-model converter should return model.DocumentFragment

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-list#60]
At the moment, List view-to-model converter returns array of model elements. We should get rid of places where array is returned in `data.output` to unify and limit possible `data.output` variations. Therefore, the converter should return `model.DocumentFragment`.

**Comment by Reinmar** [comment]
Returning arrays should be prohibited. So, you could start with https://github.com/ckeditor/ckeditor5-engine/issues/742 and implement a validation there.
