### ISSUE TITLE
Backspace at first LI should not merge with previous block

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-list#68]
Starting HTML:

```
<p>Text in paragraph</p>
<ol>
    <li>^Item 1</li>
    <li>Item 2</li>
</ol>
```

Current results after Backspace:

```
<p>Text in paragraph^Item 1</p>
<ol>
    <li>Item 2</li>
</ol>
```

Expected results:

```
<p>Text in paragraph</p>
<p>^Item 1</p>
<ol>
    <li>Item 2</li>
</ol>
```

**Comment by Reinmar** [comment]
The same feature is required for the block quote feature.

**Comment by Reinmar** [comment]
To better describe what needs to be done:

* add listener to `delete` event on the view document,
* when in the first item of a list, outdent this item and prevent default.

The same needs to be done with the block quote feature.

Example of a custom <kbd>Enter</kbd> in the list feature: https://github.com/ckeditor/ckeditor5-list/blob/master/src/list.js#L52-L62.
