### ISSUE TITLE
Conversion of a list item to model fails

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-list#70]
![jul-23-2017 22-53-34](https://user-images.githubusercontent.com/156149/28502757-cb4a2a72-6ff9-11e7-9174-4bab6540f2dd.gif)

This error is thrown most likely because we're converting a `<container:li>...</container:li>` to model and there's a check in `viewModelConverter()` which tries to get the name of li's parent.

**Comment by scofalik** [comment]
> This error is thrown most likely because we're converting a `<container:li>...</container:li>` to model and there's a check in `viewModelConverter()` which tries to get the name of li's parent.

So, you say that in this scenario, a bare `<li>` is converted (without `<ul>`)? And it's because how spellchecker works right?

**Comment by Reinmar** [comment]
If you get a bare `<li>` into the data pipeline (cause, this is what happens now – it's nearly like pasting) then we need to figure out what to do with it. You don't know if it was wrapped with ul or ol, so I think that it's absolutely ok to just guess for now.

Correct me if I'm wrong, but won't it also fix pasting such a list item?

**Comment by scofalik** [comment]
Yup it is a similar scenario.
