### ISSUE TITLE
List v->m conversion gives invalid results when list is inside disallowed elements

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-list#93]
E.g

```html
<div>
  <ul>
    <li>foo</li>
  </ul>
</div>
```

should be

```html
<ul>
  <li>foo</li>
</ul>
```

but is not converted at all or is wrapped by a paragraph when paragraph feature is enabled.

```html
<p>
  <ul>
    <li>foo</li>
  </ul>
</p>
```

**Comment by Reinmar** [comment]
> but is not converted at all or is wrapped by a paragraph when paragraph feature is enabled.

Why does the paragraph feature wrap list items? It shouldn't auto p them. Or it happens in some other way?

**Comment by oskarwrobel** [comment]
Because of bug in list converter.
1. List converter does not check schema.
2. List converter does not try to split parent element.
